# Generated by Django 4.2.11 on 2024-04-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('filiere', models.CharField(max_length=100)),
                ('numero_identification', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
