# Generated by Django 4.2.11 on 2024-05-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='filiere',
            field=models.CharField(choices=[('ABD', 'ABD'), ('APD', 'APD'), ('BDE', 'BDE'), ('DFE', 'DFE'), ('RSiot', 'RSiot'), ('SSC', 'SSC')], max_length=100),
        ),
    ]
